export type {
	ForgotPasswordBody,
	ForgotPasswordInput,
	GoogleLoginBody,
	GoogleSignupBody,
	LoginUserBody,
	LoginUserInput,
	RegisterUserBody,
	RegisterUserInput,
	ResetPasswordBody,
	ResetPasswordInput,
	UserAuthSuccess,
	VerifyRegistrationOtpBody,
	VerifyRegistrationOtpInput,
} from "../modules/auth/users/auth.types";
